export type DocContent = {
  title: string
  slug: string
  description: string
  content: string
  roles?: string[]
}

export const docsContent: DocContent[] = [
  {
    title: 'What is NexPlan?',
    slug: 'what-is-nexplan',
    description: 'An overview of NexPlan and what it does for IT infrastructure project managers.',
    roles: ['All users'],
    content: `
## Overview

NexPlan is an AI-powered IT Project Management platform built specifically for **Infrastructure Project Managers**, Network Engineers, and IT teams.

Unlike generic PM tools, NexPlan understands the language of infrastructure — from SD-WAN deployments to data centre migrations, cloud transitions, and network rollouts.

## Who is NexPlan for?

- IT Project Managers managing infrastructure projects
- Network Engineers coordinating multi-site rollouts
- Portfolio Managers overseeing multiple IT projects
- Sponsors and Stakeholders who need visibility

## What can you do with NexPlan?

- Create and manage IT projects with Kanban boards and Gantt charts
- Use AI to generate project plans, tasks, and risk assessments
- Assign tasks to team members and track progress in real-time
- Generate professional status reports with one click
- Manage risks, change requests, and post mortems
- View network diagrams generated by AI
- Access an IT-specific knowledge base

<div class="callout"><p>💡 NexPlan is free to start — no credit card required. Pro and Enterprise plans unlock AI features and advanced integrations.</p></div>
    `,
  },
  {
    title: 'How to Sign Up',
    slug: 'how-to-sign-up',
    description: 'Create your NexPlan account in under 2 minutes.',
    roles: ['All users'],
    content: `
## Creating Your Account

Getting started with NexPlan takes less than 2 minutes.

### Steps

1. Go to **nexplan.io**
2. Click **Get Started Free** or **Sign Up**
3. Enter your email address and create a password
4. You can also sign up with **Google** for instant access
5. Check your email for a verification link
6. Click the link to verify your account
7. You'll be redirected to your NexPlan dashboard

### After Sign Up

Once signed in, you'll be prompted to:
- Set your full name and role
- Select your country
- Create your first project

<div class="callout"><p>📧 If you don't receive the verification email, check your spam/junk folder. The email comes from info@nexplan.io.</p></div>
    `,
  },
  {
    title: 'How to Sign In',
    slug: 'how-to-sign-in',
    description: 'Sign in to your NexPlan account.',
    roles: ['All users'],
    content: `
## Signing In

### Email & Password
1. Go to **nexplan.io**
2. Click **Sign In**
3. Enter your email and password
4. Click **Sign In**

### Google Sign In
1. Click **Continue with Google**
2. Select your Google account
3. You'll be signed in instantly

### Forgot Password?
1. Click **Forgot password?** on the sign in page
2. Enter your email address
3. Check your email for a reset link
4. Click the link and set a new password

<div class="callout"><p>🔐 NexPlan uses Supabase Auth — your password is securely encrypted and never stored in plain text.</p></div>
    `,
  },
  {
    title: 'Account Settings',
    slug: 'account-settings',
    description: 'Update your profile, name, role and notification preferences.',
    roles: ['All users'],
    content: `
## Managing Your Account

Access your account settings by clicking your **avatar** in the top right corner → **Settings**.

### Profile Settings
- **Full Name** — update your display name
- **Email** — your login email (cannot be changed after signup)
- **Role** — your job title (IT Project Manager, Network Engineer, etc.)
- **Country** — your location

### Push Notifications
Enable push notifications to receive alerts when:
- A task is assigned to you
- A task status changes
- A task is due tomorrow
- A task becomes overdue

To enable: go to Settings → toggle **Push Notifications** → allow when your browser asks.

### Help & Support
Access the help centre and submit feedback directly from the Settings page.
    `,
  },
  {
    title: 'Plans & Pricing',
    slug: 'plans-pricing',
    description: 'Understand the Free, Pro, and Enterprise plans.',
    roles: ['All users'],
    content: `
## NexPlan Plans

### Free Plan
- Unlimited projects
- Kanban boards
- Gantt chart / Timeline
- Risk Register
- Knowledge Base (read)
- Network Diagram
- Basic reports
- Up to 3 team members

### Pro Plan — $5/month
Everything in Free, plus:
- AI Project Generator
- AI Status Reports
- AI Follow-up Emails
- AI Knowledge Base (write + generate)
- Budget Tracker
- Post Mortem Generator
- Unlimited team members
- Priority support

### Enterprise Plan
Everything in Pro, plus:
- Custom onboarding
- Dedicated support
- SSO / SAML
- Advanced analytics
- Custom integrations
- SLA guarantee

<div class="callout"><p>💳 Upgrade to Pro at any time from your dashboard. Click <strong>Upgrade to Pro</strong> in the sidebar.</p></div>
    `,
  },
  {
    title: 'Creating a Project',
    slug: 'creating-a-project',
    description: 'How to create your first IT project in NexPlan.',
    roles: ['All users'],
    content: `
## Creating a Project

### Manual Project Creation
1. Click **+ New Project** in the top right
2. Enter a project name (e.g. "London DC Migration")
3. Add a description
4. Set start and end dates (optional but recommended for Gantt chart)
5. Choose a workspace (if you have multiple)
6. Click **Create Project**

### AI Project Generation (Pro)
1. Click **+ New Project**
2. Click **🤖 AI Generate**
3. Describe your project in plain English:
   > "SD-WAN rollout across 5 UK sites, 8 weeks, 3 engineers"
4. AI generates a full project plan with tasks, priorities and timeline
5. Review and click **Import Tasks**

### Project Templates
Choose from pre-built IT infrastructure templates:
- Cloud Migration
- Data Centre Move
- Network Upgrade
- Office Relocation
- SD-WAN Deployment
- Firewall Refresh
    `,
  },
  {
    title: 'What is the Kanban Board?',
    slug: 'kanban-board',
    description: 'Understanding the Kanban board in NexPlan.',
    roles: ['All users'],
    content: `
## Kanban Board Overview

The Kanban Board is the central workspace in NexPlan. It gives you a visual overview of all tasks in your project, organised by status.

### What is Kanban?
Kanban is a visual workflow method that helps teams see work in progress, identify bottlenecks, and move tasks through stages efficiently. It originated from Toyota's manufacturing system and is now widely used in IT project management.

### NexPlan's Kanban Columns
- **🗂 Backlog** — tasks not yet started
- **⚡ In Progress** — tasks actively being worked on
- **👁 Review** — tasks awaiting review or approval
- **🚫 Blocked** — tasks that cannot proceed
- **✅ Done** — completed tasks

### Views
- **Board** — standard Kanban view
- **Timeline** — Gantt chart view

### Toolbar Features
From the Kanban toolbar you can access: PCR, Risk Register, Status Report, Alerts, Team Manager, Plan Download, Excel Export, and Budget Tracker.
    `,
  },
  {
    title: 'What is a Card?',
    slug: 'kanban-card',
    description: 'Understanding Kanban cards in NexPlan.',
    roles: ['All users'],
    content: `
## Kanban Cards

A **card** is the visual representation of a task on the Kanban board. Each card contains key information at a glance.

### What's on a Card?
- **Title** — the task name
- **Priority badge** — Low, Medium, High, or Critical
- **Tags** — custom labels for categorisation
- **Date range** — start and end dates with duration
- **Assignee avatar** — who the task is assigned to
- **Due date** — when the task must be completed
- **Activity line** — who last moved this task and when

### Interacting with Cards
- **Drag & drop** — move cards between columns to change status
- **Click "edit"** — open the full task editor
- **Activity line** — see the last action taken on the card

<div class="callout"><p>💡 The activity line at the bottom of each card shows the most recent status change — e.g. "⚡ Moved to in progress by Ram · 3 Apr 01:58"</p></div>
    `,
  },
  {
    title: 'What is a Task?',
    slug: 'what-is-a-task',
    description: 'Understanding tasks in NexPlan.',
    roles: ['All users'],
    content: `
## Tasks in NexPlan

A **task** is a unit of work within a project. Every piece of work — from configuring a router to planning a stakeholder meeting — is a task.

### Task Fields
- **Title** — what needs to be done
- **Description** — detailed notes about the task
- **Status** — Backlog, In Progress, Review, Blocked, Done
- **Priority** — Low, Medium, High, Critical
- **Assignee** — the person responsible
- **Start Date** — when work begins
- **End Date** — when work should finish
- **Due Date** — the deadline
- **Duration** — auto-calculated from start/end dates
- **Tags** — custom labels

### Task vs Card
A task is the **data**. A card is the **visual representation** of that task on the Kanban board. They are the same thing — the card is how the task looks on the board.
    `,
  },
  {
    title: 'Adding Tasks',
    slug: 'adding-tasks',
    description: 'How to add new tasks to your Kanban board.',
    roles: ['All users'],
    content: `
## Adding Tasks

### Quick Add
1. Click **+ Add card** at the bottom of any column
2. Type the task title
3. Press **Enter** to save or **Escape** to cancel

### Add Task Button
1. Click **+ Add Task** button above the board
2. A new card is added to the Backlog column
3. Click **edit** to add full details

### AI Task Generation (Pro)
1. Click **🤖 AI Generate** when creating a project
2. AI automatically creates a full set of tasks based on your project description

### Keyboard Shortcuts
- **Enter** — save new task
- **Shift+Enter** — new line in task title
- **Escape** — cancel
    `,
  },
  {
    title: 'Editing Tasks',
    slug: 'editing-tasks',
    description: 'How to edit task details in NexPlan.',
    roles: ['All users'],
    content: `
## Editing Tasks

Click **edit** on any Kanban card to open the full task editor.

### What You Can Edit
- Title and description
- Priority (Low / Medium / High / Critical)
- Assignee name and email
- Start date, end date, due date
- Tags (comma separated)

### Sending Task Notifications
When you assign a task to someone and save:
- An **email notification** is automatically sent to the assignee
- A **push notification** is sent if they have push enabled

### AI Follow-up (Pro)
Click **🤖 AI Follow-up** to send an AI-generated follow-up email to the assignee based on the task details and due date.

### Comments & Activity
The task editor has two tabs:
- **Comments** — leave notes for team members
- **Activity** — full history of all changes to this task
    `,
  },
  {
    title: 'Assigning Tasks',
    slug: 'assigning-tasks',
    description: 'How to assign tasks to team members.',
    roles: ['All users'],
    content: `
## Assigning Tasks

### From the Task Editor
1. Click **edit** on any card
2. In the **Assignee** dropdown — select an organisation member
3. Their name and email are auto-populated
4. Click **Save Changes**
5. The assignee receives an automatic email and push notification

### What Happens After Assignment
- The task appears in the assignee's **My Tasks** page
- The assignee can update the task status from My Tasks
- Any status change they make is reflected on the Kanban board
- The card shows: *"👤 Assigned to [name] by [you] · [date]"*

<div class="callout"><p>💡 Only organisation members can be assigned tasks. Invite team members first via Organisation → Invite Member.</p></div>
    `,
  },
  {
    title: 'Drag & Drop',
    slug: 'drag-drop',
    description: 'Moving tasks between columns using drag and drop.',
    roles: ['All users'],
    content: `
## Drag & Drop

### Moving Tasks
1. Click and hold a task card
2. Drag it to a different column
3. Release to drop it in the new status

### What Happens
- The task status updates instantly in the database
- The activity log records who moved it and when
- The card shows the new status immediately

### Reordering Within a Column
You can also reorder tasks within the same column by dragging them up or down.

### Mobile
On mobile, tap and hold a task card for 0.5 seconds to trigger the **Move To** sheet, then select the destination column.
    `,
  },
  {
    title: 'Task Activity Log',
    slug: 'task-activity',
    description: 'Track who changed what and when on every task.',
    roles: ['All users'],
    content: `
## Task Activity Log

Every change to a task is automatically recorded in the activity log.

### What is Tracked
- Status changes (who moved it, to where, when)
- Assignee changes
- Priority changes
- Due date changes
- Title changes

### Where to See Activity
- **On the Kanban card** — the bottom line shows the most recent status change
- **In the task editor** — click the **Activity** tab for full history

### Example Activity
> ⚡ Moved to in progress by Ram · 3 Apr 01:58

This tells you exactly who took action, what they did, and when — giving full accountability across your team.
    `,
  },
  {
    title: 'My Tasks Overview',
    slug: 'my-tasks',
    description: 'View and manage all tasks assigned to you.',
    roles: ['All users'],
    content: `
## My Tasks

The **My Tasks** page shows every task assigned to you across all projects.

### Accessing My Tasks
Click **My Tasks** in the left sidebar.

### What You See
- **Stats bar** — Total, In Progress, Due Soon, Overdue, Completed counts
- **Task cards** — all your assigned tasks
- **Overdue tasks** — highlighted in red with a red left border

### Task Card Actions
- **Click the status badge** — advances the task to the next status instantly
- Status updates are reflected immediately on the Kanban board
    `,
  },
  {
    title: 'Filtering & Grouping',
    slug: 'my-tasks-filters',
    description: 'Filter and group your tasks in My Tasks.',
    roles: ['All users'],
    content: `
## Filtering Your Tasks

### Search
Type in the search box to filter tasks by title.

### Filter Dropdowns
- **Status** — All, To Do, In Progress, In Review, Done
- **Priority** — All, Urgent, High, Medium, Low
- **Project** — All projects or a specific project

### Group By
Switch the grouping using the dropdown in the top right:
- **By Status** — grouped by task status
- **By Priority** — grouped by priority level
- **By Project** — grouped by which project
- **By Due Date** — grouped as Overdue, Today, This Week, Later

### Clearing Filters
Click **Clear (n)** to reset all active filters at once.
    `,
  },
  {
    title: 'Timeline View',
    slug: 'timeline-view',
    description: 'View your project as a timeline.',
    roles: ['All users'],
    content: `
## Timeline View

The Timeline view shows all tasks with dates plotted on a visual Gantt chart.

### Switching to Timeline
On the Kanban board, click the **Timeline** tab in the toolbar.

### Requirements
- Your project must have a **Start Date** and **End Date** set
- Tasks must have individual start and end dates to appear on the chart

### Setting Task Dates
1. Click **edit** on any task card
2. Set **Start Date** and **End Date**
3. Duration is auto-calculated
4. Save the task — it now appears on the Gantt chart

### Unscheduled Tasks
Tasks without dates appear in the **Unscheduled Tasks** section below the chart. Click them to add dates.
    `,
  },
  {
    title: 'Gantt Chart',
    slug: 'gantt-chart',
    description: 'Understanding and using the Gantt chart in NexPlan.',
    roles: ['All users'],
    content: `
## Gantt Chart

The Gantt chart provides a visual project timeline with day-by-day task scheduling.

### Reading the Gantt Chart
- Each row represents a task
- Each bar represents the task duration
- Bar colour indicates status (blue = in progress, green = done, amber = review, red = blocked)
- A vertical **TODAY** line shows the current date
- Progress percentage is shown inside each bar

### Summary Bar
At the top of the Gantt view:
- Target date
- Total project duration
- Tasks completed vs total
- Overall progress bar

### Critical Path
The bottom of the chart highlights the **Critical Path** — the sequence of tasks that determines the minimum project duration.
    `,
  },
  {
    title: 'Exporting Gantt',
    slug: 'exporting-gantt',
    description: 'Export your Gantt chart as CSV, TXT or PNG.',
    roles: ['All users'],
    content: `
## Exporting Your Gantt Chart

NexPlan supports three export formats from the Timeline view.

### Export Formats
- **📄 TXT** — formatted text report with task schedule and progress bars
- **📊 CSV** — spreadsheet-compatible export with all task data
- **🖼️ PNG** — visual screenshot of the Gantt chart with NexPlan watermark

### How to Export
1. Switch to **Timeline** view on the Kanban board
2. Click **TXT**, **CSV**, or **PNG** buttons in the summary bar
3. The file downloads automatically

### Excel Export
For a full project export including all task details, use the **Excel** button in the Kanban toolbar.
    `,
  },
  {
    title: 'Inviting Team Members',
    slug: 'inviting-members',
    description: 'How to invite colleagues to your NexPlan organisation.',
    roles: ['Admin', 'PM'],
    content: `
## Inviting Team Members

### Via Organisation Settings
1. Click **Organisation** in the left sidebar
2. Click **Invite Member**
3. Enter their email address
4. Select their role (PM, Viewer, etc.)
5. Click **Send Invite**
6. They receive an email with a join link

### Via Join Link
1. Go to Organisation settings
2. Generate a **Join Link**
3. Share the link directly with your team
4. They click the link and join your organisation automatically

### Assigning Invited Members to Tasks
Once they accept the invite, they appear in the **Assignee** dropdown when editing tasks.

<div class="callout"><p>💡 Only organisation admins can invite new members. Members can view and update tasks but cannot manage organisation settings.</p></div>
    `,
  },
  {
    title: 'Roles & Permissions',
    slug: 'roles-permissions',
    description: 'Understanding roles in NexPlan.',
    roles: ['Admin'],
    content: `
## Roles & Permissions

### Organisation Roles
- **Org Admin** — full access, can invite members, manage settings, view all projects
- **PM (Project Manager)** — can create and manage projects, assign tasks, generate reports
- **Viewer** — read-only access to projects they are added to

### Project Roles
- **Owner** — the user who created the project; full control
- **PM** — can edit tasks, change statuses, assign members
- **Member** — can update task statuses assigned to them

### What Each Role Can Do
| Action | Admin | PM | Viewer |
|---|---|---|---|
| Create projects | ✅ | ✅ | ❌ |
| Invite members | ✅ | ❌ | ❌ |
| Delete projects | ✅ | ✅ (own) | ❌ |
| View all projects | ✅ | Own only | Shared only |
| Export reports | ✅ | ✅ | ❌ |
    `,
  },
  {
    title: 'AI Knowledge Base',
    slug: 'ai-knowledge-base',
    description: 'Use the AI-powered knowledge base for IT infrastructure topics.',
    roles: ['All users', 'Pro'],
    content: `
## AI Knowledge Base

The NexPlan Knowledge Base contains **55+ IT infrastructure articles** covering networking, cloud, security, server management, and more.

### Accessing the Knowledge Base
Click **Knowledge Base** in the left sidebar.

### Browsing Articles
Articles are organised by category:
- Networking
- Security
- Cloud
- Server & VM
- Project Management
- Office Move
- Migration
- Runbooks
- Wireless
- Storage

### Reading & Downloading
- Click **Read** to open the full article
- Click **Download** to save as a text file

### AI Article Generation (Pro)
1. Click **+ New Article**
2. Describe the topic you need
3. AI generates a comprehensive IT article
4. Articles are saved to your knowledge base
    `,
  },
  {
    title: 'Risk Register',
    slug: 'risk-register',
    description: 'Manage project risks with the built-in Risk Register.',
    roles: ['All users'],
    content: `
## Risk Register

The Risk Register helps you identify, assess, and manage risks in your IT project.

### Accessing the Risk Register
On the Kanban board, click **Risks** in the toolbar.

### Adding a Risk
1. Click **+ Add Risk**
2. Enter:
   - Risk description
   - Likelihood (Low / Medium / High)
   - Impact (Low / Medium / High)
   - Mitigation plan
3. Save the risk

### Risk Score
NexPlan automatically calculates a **risk score** based on likelihood × impact, helping you prioritise which risks to address first.

### AI Risk Generation (Pro)
Click **🤖 Generate Risks** to have AI automatically identify risks based on your project type and tasks.
    `,
  },
  {
    title: 'Project Change Requests (PCR)',
    slug: 'pcr',
    description: 'Manage change requests with the PCR module.',
    roles: ['All users'],
    content: `
## Project Change Requests (PCR)

PCRs allow you to formally track and approve changes to project scope, timeline, or budget.

### Requirements
Your project must have a **Start Date** and **End Date** set before creating PCRs.

### Creating a PCR
1. Click **PCR** in the Kanban toolbar
2. Click **+ New Change Request**
3. Fill in:
   - Change title
   - Description
   - Impact on timeline
   - Impact on budget
   - Reason for change
4. Submit for approval

### PCR Statuses
- **Pending** — awaiting review
- **Approved** — change accepted
- **Rejected** — change declined
    `,
  },
  {
    title: 'Push Notifications',
    slug: 'push-notifications',
    description: 'Enable push notifications for task alerts.',
    roles: ['All users'],
    content: `
## Push Notifications

NexPlan supports browser push notifications so you stay informed even when the app is not open.

### Enabling Push Notifications
1. Go to **Settings** (click your avatar → Settings)
2. Find the **Push Notifications** toggle
3. Click to enable
4. When your browser asks "Allow notifications?" — click **Allow**
5. The toggle turns blue — you're subscribed ✅

### What You'll Be Notified About
- 📋 **Task Assigned** — when someone assigns a task to you
- 🔄 **Task Updated** — when a task you're assigned to changes status
- ⏰ **Due Tomorrow** — 24 hours before a task is due
- 🚨 **Overdue** — when a task passes its due date

### Mobile Push Notifications
- **Android** — works automatically in Chrome
- **iOS** — requires NexPlan to be installed as a PWA (Add to Home Screen in Safari)

### Disabling Notifications
Toggle the Push Notifications switch off in Settings to unsubscribe.
    `,
  },
  {
    title: 'Installing NexPlan (PWA)',
    slug: 'pwa-install',
    description: 'Install NexPlan on your device as a Progressive Web App.',
    roles: ['All users'],
    content: `
## Installing NexPlan as an App

NexPlan is a **Progressive Web App (PWA)** — meaning you can install it on any device and use it like a native app, with no App Store required.

### Desktop (Chrome / Edge)
1. Go to **nexplan.io**
2. Look for the **install icon** (⊕) in the address bar
3. Click it → **Install NexPlan**
4. The app opens as a standalone window without the browser bar

### Android (Chrome)
1. Open **nexplan.io** in Chrome
2. Tap the **3-dot menu** → **Add to Home Screen**
3. Tap **Install**
4. NexPlan icon appears on your home screen

### iOS (Safari)
1. Open **nexplan.io** in Safari
2. Tap the **Share button** (box with arrow)
3. Scroll down → **Add to Home Screen**
4. Tap **Add**
5. NexPlan icon appears on your home screen

<div class="callout"><p>📱 No App Store needed. NexPlan installs directly from your browser and works offline for cached pages.</p></div>
    `,
  },
  {
    title: 'Admin Panel Overview',
    slug: 'admin-panel',
    description: 'Overview of the NexPlan admin panel.',
    roles: ['Admin'],
    content: `
## Admin Panel

The Admin Panel is accessible only to **info@nexplan.io** (the platform admin).

### Accessing the Admin Panel
Click **Admin** in the left sidebar (visible to admin only).

### Admin Panel Tabs

#### Users
- View all registered users
- See their plan (Free / Pro / Enterprise)
- View their role, country, and IP address
- Monitor total user count

#### Audit Log
- Full audit trail of all user actions
- Filter by user, action type, date
- Track AI usage, logins, project creation, task changes

#### Subscriptions
- View all active Pro and Enterprise subscriptions
- Monitor payment status via Dodo Payments

### User Data Captured
For each user:
- Email
- Plan
- Role
- Country (selected by user)
- Country (detected from IP)
- IP Address
- Last login
    `,
  },
]

// ─── Additional doc pages ─────────────────────────────────────────────────────

export const docsContentExtra: DocContent[] = [
  {
    title: 'Project Settings',
    slug: 'project-settings',
    description: 'Configure your project settings, dates, budget and more.',
    roles: ['All users'],
    content: `
## Project Settings

Access project settings by clicking the project name dropdown on the Kanban board, then clicking the **📅 date pill** or the settings icon.

### What You Can Configure
- Project name and description
- Start date and end date
- Project colour
- Budget (currency, total, contingency)
- Stakeholder emails for reports
- Report frequency
- Attachment / project document

### Setting Project Dates
Project dates are required for the Gantt chart and PCR module.
1. Click the date pill next to the project name on the Kanban board
2. Set Start Date and End Date
3. Click Save Project

### Budget Settings
Enable the Budget Tracker by setting a total project budget. You can also set a contingency buffer percentage. Once set, the 💰 Budget Tracker button appears in the Kanban toolbar.
    `,
  },
  {
    title: 'AI Project Generator',
    slug: 'ai-project-generator',
    description: 'Generate a full project plan using AI in seconds.',
    roles: ['Pro'],
    content: `
## AI Project Generator

The AI Project Generator creates a complete project plan — including tasks, priorities, and timeline — from a plain English description.

### How to Use
1. Click **+ New Project**
2. Click **🤖 AI Generate**
3. Enter your project description:
   > "Cloud migration of 3 on-premise servers to AWS, 6 weeks, 2 engineers"
4. Set start and end dates
5. Click **Generate**
6. Review the AI-generated tasks
7. Click **Import Tasks** to add them to your board

### What AI Generates
- 10–20 tasks with titles and descriptions
- Priority levels (Low / Medium / High / Critical)
- Suggested task order
- Dependencies identified

<div class="callout"><p>🤖 AI Project Generator is a Pro feature. Upgrade to Pro to access it.</p></div>
    `,
  },
  {
    title: 'Project Dates & Timeline',
    slug: 'project-dates',
    description: 'Set project start and end dates to unlock the Gantt chart.',
    roles: ['All users'],
    content: `
## Project Dates

Setting project dates unlocks the Timeline/Gantt view and is required for PCRs.

### How to Set Project Dates
1. On the Kanban board, click the **📅 date pill** next to the project name
2. Set **Start Date** and **End Date**
3. Click **Save Project**

### Task Dates vs Project Dates
- **Project dates** — the overall project start and finish
- **Task dates** — individual task start/end dates that appear on the Gantt

Tasks without dates appear in the **Unscheduled Tasks** section on the Timeline view.

### Duration Calculation
Duration is automatically calculated as End Date minus Start Date + 1 day.
    `,
  },
  {
    title: 'Budget Tracker',
    slug: 'budget-tracker',
    description: 'Track planned vs actual spend on your IT project.',
    roles: ['Pro'],
    content: `
## Budget Tracker

The Budget Tracker helps you monitor project spend against your approved budget.

### Enabling the Budget Tracker
1. Open project settings (click the date pill on the Kanban board)
2. Go to the **Budget** tab
3. Select currency (USD, GBP, EUR, INR, AED, SGD)
4. Enter total project budget
5. Set contingency buffer percentage (5%–25%)
6. Save — the 💰 Budget Tracker button appears in the toolbar

### Budget Overview
The Budget Tracker shows:
- Total budget
- Contingency reserve
- Effective budget (after contingency)
- At-risk spend based on blocked/overdue tasks
- Schedule overrun cost estimate

<div class="callout"><p>💰 Budget Tracker is a Pro feature.</p></div>
    `,
  },
  {
    title: 'Columns & Statuses',
    slug: 'kanban-columns',
    description: 'Understanding the five Kanban columns in NexPlan.',
    roles: ['All users'],
    content: `
## Kanban Columns

NexPlan uses five columns representing the lifecycle of a task.

### The Five Columns
- **🗂 Backlog** — tasks not yet started; the default column for new tasks
- **⚡ In Progress** — tasks actively being worked on right now
- **👁 Review** — tasks awaiting sign-off, testing, or peer review
- **🚫 Blocked** — tasks that cannot proceed due to a dependency or issue
- **✅ Done** — completed tasks

### Moving Tasks Between Columns
- **Desktop** — drag and drop the card to the target column
- **Mobile** — long press a card → select destination from Move To sheet

### Column Counts
Each column header shows the number of tasks it contains. This helps identify bottlenecks — if Blocked has many tasks, it needs attention.
    `,
  },
  {
    title: 'Quick Status Update',
    slug: 'quick-status-update',
    description: 'Update task status with one tap from My Tasks.',
    roles: ['All users'],
    content: `
## Quick Status Update

From the **My Tasks** page, you can advance a task's status with a single click — without opening the full editor.

### How It Works
1. Go to **My Tasks** in the sidebar
2. Find the task you want to update
3. Click the **status badge** (e.g. "To Do", "In Progress")
4. The status advances to the next stage instantly

### Status Progression
- To Do → In Progress
- In Progress → Done
- In Review → Done
- Done → To Do (cycles back)

### Real-time Sync
The status change is:
- Saved to the database immediately
- Reflected on the Kanban board instantly
- Logged in the task activity log
- Visible to the project owner on their board
    `,
  },
  {
    title: 'Critical Path',
    slug: 'critical-path',
    description: 'Understand the critical path in your Gantt chart.',
    roles: ['All users'],
    content: `
## Critical Path

The critical path is the sequence of tasks that determines the **minimum time** to complete the project.

### Where to Find It
The critical path is shown at the bottom of the Gantt chart in the Timeline view, highlighted in red.

### How NexPlan Calculates It
NexPlan identifies the task(s) with the latest end date and traces back through the project schedule to highlight the chain of tasks that must complete on time for the project to finish by the target date.

### Why It Matters
Tasks on the critical path have zero float — any delay to these tasks directly delays the project end date. Focus your risk management and monitoring on critical path tasks.
    `,
  },
  {
    title: 'Organisation Dashboard',
    slug: 'org-dashboard',
    description: 'View your organisation portfolio from the dashboard.',
    roles: ['Admin', 'PM'],
    content: `
## Organisation Dashboard

The Organisation Dashboard gives admins and PMs a portfolio-level view across all projects.

### Accessing It
Click **Organisation** → **Dashboard** in the left sidebar.

### What You See
- Total workspaces and projects
- Total tasks and completion percentage
- At-risk and overdue task counts
- Portfolio completion progress bar
- Client workspaces breakdown
- Per-project status summary

### Portfolio Metrics
- **Completion %** — based on Done tasks vs total tasks
- **At Risk** — tasks that are blocked or overdue
- **On Track** — projects progressing normally
    `,
  },
  {
    title: 'Workspaces',
    slug: 'workspaces',
    description: 'Organise projects into workspaces for different clients or teams.',
    roles: ['Admin', 'PM'],
    content: `
## Workspaces

Workspaces let you group projects by client, team, or business unit.

### Creating a Workspace
1. Go to **Organisation** in the sidebar
2. Click **+ New Workspace**
3. Enter workspace name and client name
4. Assign a colour for visual identification
5. Save

### Assigning Projects to Workspaces
When creating a new project, select a workspace from the dropdown. Projects in the same workspace are grouped together in the Organisation Dashboard.

### Use Cases
- Separate workspaces per client (e.g. "Accenture", "NTT Data")
- Separate by team (e.g. "Network Team", "Cloud Team")
- Separate by region (e.g. "UK Projects", "US Projects")
    `,
  },
  {
    title: 'AI Project Manager',
    slug: 'ai-project-manager',
    description: 'Use the AI assistant to get project management advice.',
    roles: ['Pro'],
    content: `
## AI Project Manager

The AI Project Manager is your intelligent assistant for IT project planning and management.

### Accessing It
Click the **🤖 AI** button available on the Kanban board and Knowledge Base.

### What You Can Ask
- "Generate a risk register for a cloud migration project"
- "What tasks are typically involved in a firewall refresh?"
- "Create a checklist for office network relocation"
- "Summarise the current project status"

### AI Capabilities
- Generate project plans from descriptions
- Create task lists for specific IT scenarios
- Provide IT infrastructure best practices
- Generate status summaries
- Suggest risk mitigations

<div class="callout"><p>🤖 AI Project Manager requires a Pro plan.</p></div>
    `,
  },
  {
    title: 'AI Status Reports',
    slug: 'ai-status-reports',
    description: 'Generate professional project status reports with AI.',
    roles: ['Pro'],
    content: `
## AI Status Reports

Generate a professional project status report in seconds using AI.

### How to Generate
1. On the Kanban board, click **📊 Report** in the toolbar
2. Click **Generate AI Report**
3. AI analyses your current tasks, progress, risks, and timeline
4. A formatted report is generated instantly

### What the Report Includes
- Executive summary
- Progress overview (% complete)
- Tasks completed this period
- Tasks in progress
- Blocked items and risks
- Upcoming milestones
- Recommendations

### Sending Reports
- **Email** — send directly to stakeholders
- **Download** — save as PDF or Word document

<div class="callout"><p>📊 AI Status Reports are a Pro feature.</p></div>
    `,
  },
  {
    title: 'AI Follow-up Emails',
    slug: 'ai-followup',
    description: 'Send AI-generated follow-up emails to task assignees.',
    roles: ['Pro'],
    content: `
## AI Follow-up Emails

Send professionally written follow-up emails to task assignees automatically.

### How to Use
1. Open any task editor (click **edit** on a card)
2. Click **🤖 AI Follow-up**
3. AI generates a personalised email based on:
   - Task title and description
   - Assignee name
   - Due date
   - Current priority
4. Review the email
5. Click **Send**

### When to Use
- Task is approaching its due date
- Task has been in progress for a long time
- You need a professional reminder without writing it yourself

<div class="callout"><p>📧 AI Follow-up requires a Pro plan and the task must have an assignee email and due date set.</p></div>
    `,
  },
  {
    title: 'Change Freeze Calendar',
    slug: 'change-freeze',
    description: 'Block out change freeze periods to prevent scheduling conflicts.',
    roles: ['Admin', 'PM'],
    content: `
## Change Freeze Calendar

The Change Freeze Calendar lets you mark periods when no infrastructure changes should be scheduled — such as financial year-end, holiday periods, or critical business events.

### Accessing It
Go to **Settings** → scroll down to the **Change Freeze Calendar** section.

### Adding a Freeze Period
1. Click on a date or date range in the calendar
2. Enter a description (e.g. "Year-end freeze", "Christmas blackout")
3. Save

### How It Helps
- Visually blocks out periods when tasks should not be scheduled
- Prevents PMs from accidentally scheduling risky changes during critical periods
- Admins can set org-wide freezes; PMs can set project-specific ones

<div class="callout"><p>🧊 Change freeze periods are visible to all organisation members.</p></div>
    `,
  },
  {
    title: 'Post Mortem Generator',
    slug: 'post-mortem',
    description: 'Generate a post mortem report after project completion.',
    roles: ['Pro'],
    content: `
## Post Mortem Generator

Generate a structured post mortem (lessons learned) report at the end of a project.

### Accessing It
On the Kanban board, click **📋 PCR** → **Post Mortem** tab, or look for the Post Mortem button in the toolbar.

### What It Generates
- Project summary (timeline, budget, team)
- What went well
- What could be improved
- Key lessons learned
- Recommendations for future projects
- Risk items that materialised

### Exporting
Download the post mortem as a PDF or Word document to share with stakeholders or store in your knowledge base.

<div class="callout"><p>🔎 Post Mortem Generator is a Pro feature.</p></div>
    `,
  },
  {
    title: 'Reports Overview',
    slug: 'reports',
    description: 'Generate and view project reports in NexPlan.',
    roles: ['All users'],
    content: `
## Reports

NexPlan provides multiple reporting options to keep stakeholders informed.

### Accessing Reports
Click **Reports** in the left sidebar.

### Report Types
- **Status Report** — current project health, tasks, risks
- **Progress Report** — completion percentage over time
- **Team Report** — tasks per assignee
- **Risk Report** — open risks and mitigations
- **Budget Report** — spend vs budget (if budget set)

### Automated Reports
Set up automated weekly reports in project settings:
1. Open project settings
2. Set **Report Frequency** (weekly, bi-weekly, monthly)
3. Add **Stakeholder Emails**
4. Set **Report Day**
5. Reports are sent automatically on schedule
    `,
  },
  {
    title: 'Analytics Dashboard',
    slug: 'analytics',
    description: 'View usage analytics and project insights.',
    roles: ['All users'],
    content: `
## Analytics Dashboard

The Analytics Dashboard provides insights into project performance and team productivity.

### Accessing It
Click **Analytics** in the left sidebar.

### What You Can See
- Task completion rate over time
- Tasks by status breakdown
- Tasks by priority breakdown
- Team member productivity
- Project velocity
- Overdue task trends

### Filtering
Filter analytics by:
- Date range
- Project
- Team member
    `,
  },
  {
    title: 'Export to Excel',
    slug: 'export-excel',
    description: 'Export your project tasks to an Excel spreadsheet.',
    roles: ['All users'],
    content: `
## Export to Excel

Export all project tasks to a formatted Excel (.xlsx) file.

### How to Export
1. On the Kanban board, click **📊 Excel** in the toolbar
2. The file downloads automatically

### What's Included
- Task title and description
- Status and priority
- Assignee name and email
- Start date, end date, due date
- Duration
- Tags

### Use Cases
- Share with stakeholders who don't use NexPlan
- Create offline backups
- Perform custom analysis in Excel
    `,
  },
  {
    title: 'Export to PDF',
    slug: 'export-pdf',
    description: 'Export your project plan as a PDF document.',
    roles: ['All users'],
    content: `
## Export to PDF

Export your project as a professionally formatted PDF.

### How to Export
1. On the Kanban board, click **📋 Plan** in the toolbar
2. Select **Export PDF**
3. The PDF downloads automatically

### What's Included
- Project summary
- Task list by status
- Gantt chart (if dates are set)
- Risk register summary
- NexPlan branding and watermark
    `,
  },
  {
    title: 'Export to PowerPoint',
    slug: 'export-ppt',
    description: 'Export your project as a PowerPoint presentation.',
    roles: ['All users'],
    content: `
## Export to PowerPoint

Generate a PowerPoint presentation from your project data.

### How to Export
1. On the Kanban board, click **📋 Plan** in the toolbar
2. Select **Export PPT**
3. The .pptx file downloads automatically

### Slides Generated
- Title slide with project name
- Executive summary
- Project status and progress
- Task breakdown by status
- Key risks
- Timeline summary

### Use Cases
- Stakeholder presentations
- Project steering committee updates
- Client reporting
    `,
  },
  {
    title: 'Network Diagram Overview',
    slug: 'network-diagram',
    description: 'Visualise your IT network infrastructure with NexPlan.',
    roles: ['All users'],
    content: `
## Network Diagram

The Network Diagram feature lets you create and visualise IT infrastructure topology diagrams.

### Accessing It
Click **Network Diagram** in the left sidebar.

### Creating a Diagram
- **Manual** — drag and drop network nodes (routers, switches, servers, firewalls, etc.)
- **AI Generate** — describe your network and AI creates the diagram

### Node Types
- Routers
- Switches
- Firewalls
- Servers
- Cloud services
- End user devices
- WAN/ISP connections

### Exporting
Export your network diagram as a PNG image for use in project documentation or stakeholder presentations.
    `,
  },
  {
    title: 'AI Network Generator',
    slug: 'ai-network-generator',
    description: 'Generate network topology diagrams using AI.',
    roles: ['Pro'],
    content: `
## AI Network Generator

Describe your network infrastructure in plain English and AI generates a visual network diagram.

### How to Use
1. Go to **Network Diagram** in the sidebar
2. Click **🤖 AI Generate**
3. Describe your network:
   > "Head office with 2 core switches, 3 access switches, 1 firewall, connected to 2 remote sites via MPLS"
4. AI generates the diagram with appropriate nodes and connections
5. Edit nodes manually if needed
6. Export as PNG

<div class="callout"><p>🤖 AI Network Generator is a Pro feature.</p></div>
    `,
  },
  {
    title: 'Email Notifications',
    slug: 'email-notifications',
    description: 'Understand email notifications sent by NexPlan.',
    roles: ['All users'],
    content: `
## Email Notifications

NexPlan sends automatic emails to keep your team informed.

### Automatic Emails Sent
- **Task Assignment** — when a task is assigned to you
- **Invite** — when you are invited to join an organisation
- **Welcome** — when you create a new account
- **Pro Welcome** — when you upgrade to Pro
- **Status Report** — automated weekly/monthly project reports

### Email From Address
All emails are sent from **info@nexplan.io** via Resend.

### Unsubscribing
To stop receiving task assignment emails, ask your organisation admin to update notification settings. Automated status reports can be disabled in project settings.
    `,
  },
  {
    title: 'Task Reminders',
    slug: 'task-reminders',
    description: 'Automatic task reminders for due dates and overdue tasks.',
    roles: ['All users'],
    content: `
## Task Reminders

NexPlan automatically sends reminders for upcoming and overdue tasks.

### When Reminders Are Sent
- **Due Tomorrow** — push notification sent the day before a task is due
- **Overdue** — push notification sent each day a task remains overdue

### How Reminders Work
Reminders are sent daily at **8:00 AM** via the automated cron job. They are delivered as push notifications to all users who have enabled push notifications in Settings.

### Enabling Reminders
1. Go to **Settings**
2. Enable **Push Notifications**
3. Allow browser notification permission
4. You will automatically receive due date reminders

<div class="callout"><p>⏰ Task reminders require push notifications to be enabled in your browser settings.</p></div>
    `,
  },
  {
    title: 'Mobile Kanban',
    slug: 'mobile-kanban',
    description: 'Use the Kanban board on your mobile device.',
    roles: ['All users'],
    content: `
## Mobile Kanban

NexPlan's Kanban board is optimised for mobile with a swipe-based interface.

### Mobile Layout
On mobile screens, the Kanban board shows **one column at a time** instead of all columns side by side.

### Navigating Columns
- **Swipe left** — go to the next column
- **Swipe right** — go to the previous column
- **Tab pills** — tap any column pill at the top to jump directly to it
- **Dot indicators** — show which column you're currently viewing

### Working with Tasks on Mobile
- **Tap a task** — opens the full task editor (all fields, dates, assignee)
- **Long press a task** — shows the Move To sheet to change the task's column

### Installing NexPlan on Mobile
For the best mobile experience, install NexPlan as a PWA. See **Installing NexPlan (PWA)** for instructions.
    `,
  },
  {
    title: 'Managing Users',
    slug: 'managing-users',
    description: 'Admin guide to managing NexPlan users.',
    roles: ['Admin'],
    content: `
## Managing Users

The Admin Panel gives you full visibility and control over all NexPlan users.

### Accessing User Management
Click **Admin** in the sidebar → **Users** tab.

### User Information Displayed
- Email address
- Plan (Free / Pro / Enterprise)
- Role (IT Project Manager, Network Engineer, etc.)
- Country (selected by user)
- Country (detected from IP address)
- IP address

### User Count
The total user count is shown at the top: e.g. "25 total · Page 1 of 2"

### Searching Users
Use the search box to find a specific user by email or name.

### Plan Management
Pro and Enterprise subscriptions are managed via Dodo Payments. View subscription status in the **Subscriptions** tab.
    `,
  },
  {
    title: 'Audit Logs',
    slug: 'audit-logs',
    description: 'View a full audit trail of all user actions in NexPlan.',
    roles: ['Admin'],
    content: `
## Audit Logs

The Audit Log records every significant action taken in NexPlan.

### Accessing Audit Logs
Click **Admin** → **Audit Log** tab.

### What is Logged
- User logins
- Project creation and deletion
- Task creation, updates, status changes
- AI feature usage
- Report generation
- Invite sent/accepted

### Log Fields
- Timestamp
- User email and name
- Action type
- Feature used
- Project name
- Status (success/error)

### Filtering
Filter the audit log by:
- User
- Action type
- Date range
- Project
    `,
  },
  {
    title: 'Subscriptions',
    slug: 'subscriptions',
    description: 'Manage Pro and Enterprise subscriptions.',
    roles: ['Admin'],
    content: `
## Subscriptions

NexPlan uses **Dodo Payments** to process Pro and Enterprise subscriptions.

### Viewing Subscriptions
Click **Admin** → **Subscriptions** tab to see all active paying customers.

### Upgrading to Pro
Users can upgrade by clicking **Upgrade to Pro** in the sidebar or on the Pricing page. Payment is processed securely via Dodo Payments.

### Cancelling a Subscription
Users can cancel their subscription from the billing portal. After cancellation, they retain Pro access until the end of the billing period.

### Enterprise Plans
Enterprise plans include custom pricing and onboarding. Contact **info@nexplan.io** to discuss Enterprise.

<div class="callout"><p>💳 All payments are processed securely by Dodo Payments. NexPlan never stores card details.</p></div>
    `,
  },
]
